### ISSUE TITLE
Double click select variable without variabletype

### ISSUE THREAD

**Issue by Fank** [atom/language-perl#18]
If i double click on a variable `my $test` i want select the variable name and the variable type `$test`, but it will only select `test` without the variable type.
This decrease the usability because you need the variable type in about 90%.

Same with `my @test` etc.

@kevinsawicki I tried a lot of changes, but it looks like this isn't related to this repo. Any idea where does it need to be changed?

**Comment by kevinsawicki** [comment]
>  Any idea where does it need to be changed?

There is a setting in the settings view for "non word characters" which controls this.

![screen shot 2015-03-19 at 9 42 20 am](https://cloud.githubusercontent.com/assets/671378/6735568/44c42ff6-ce1c-11e4-9159-dd93b27490c1.png)

The default is here: https://github.com/atom/atom/blob/dccf88063bf9241d83250554a8427ceb4b437389/src/config-schema.coffee#L132-L134

**Comment by Fank** [comment]
So a language dependent non word characters would be a feature for this or?

**Comment by thomasjo** [comment]
> So a language dependent non word characters would be a feature for this or?

That already exists. Just check the settings view for e.g. `language-perl`. I don't know whether the default there can be (easily) changed per package. But I suspect it might be, since it can be overridden on a per grammar basis.
