### ISSUE TITLE
Add variable highlighting in 'qq'

### ISSUE THREAD

**Issue by Fank** [atom/language-perl#19]
![var_highlight](https://cloud.githubusercontent.com/assets/1900106/6624165/dbbcef36-c8e7-11e4-98f3-38025f729788.png)
Github highlight does it right:
```perl
my $foo = qq(
This is my $var
Or my @array
);
```

`$var` and `@array` should be highlighted

**Comment by Fank** [comment]
@50Wliu could you please explain the difference between bug and * because this issue more looks like an improvement instead of a bug.

**Comment by 50Wliu** [comment]
Hmm, looks like you're right.  I think your syntax theme caught me off guard.

**Comment by 50Wliu** [comment]
@Fank I think you fixed this recently?

**Comment by Fank** [comment]
Nope ill work on this soon, i fixed the escape issue in q (single quote)

**Comment by Fank** [comment]
hm, this looks like to be fixed. I think this was an issue in the old syntax highlighting.
