### ISSUE TITLE
Multiline RegEx clobbers highlighting

### ISSUE THREAD

**Issue by Alhadis** [atom/language-perl#47]
Observe:
```perl
my $line;
while(<>){
	chomp;
	$line =		$_;

	# Delete control characters
	$line =~	s/[
		\x{00}-\x{08}
	]//gx;

	say $line;
}
```
Becomes:
![figure-1](https://cloud.githubusercontent.com/assets/2346707/8447519/8a74e2ec-1ffd-11e5-8b0a-51aafd10ee98.png)

Adding or removing the `/gx` modifiers has no impact on the overzealous highlighting, either.

### System specs:
* **Platform:** Mac OS/X 10.9.5 (Screw Yosemite)
* **Processor:** 2.3 GHz Intel Core i7
* **Memory:** 16 GB 1600 MHz DDR3
* **Atom version:** 1.0.0

# Update
I've noticed that highlighting won't spill across lines if there's at least one extra delimiter on the first line. 

For instance, this is okay:
![figure-2](https://cloud.githubusercontent.com/assets/2346707/8447495/fd0f7d72-1ffc-11e5-930d-1bdc6ad32c74.png)

But not this:
![figure-3](https://cloud.githubusercontent.com/assets/2346707/8447497/091c112a-1ffd-11e5-80cb-c51dc5caca11.png)

**Comment by Fank** [comment]
Thanks for reporting, I located the problem and fixed it in the attached pull request.
