### ISSUE TITLE
Syntax highlighting fails at regexes

### ISSUE THREAD

**Issue by alexchandel** [atom/language-perl#53]
The following valid regex, placed in a short Perl script, causes Atom's Perl highlighting to fail for everything afterwards:

```perl
say "this is highlighted correctly";

/((?:"[^"]*")+|[^$foo]*)(?:$bar|$)/gs;

say "this isn't";
```

**Comment by Fank** [comment]
This should be fixed by migrating the regex highlighting from perl to perl6.
Tested in perl and it works fine, but not in perl6.

**Comment by alexchandel** [comment]
I was using `Perl`, not `Perl 6`, when this bug happened.

**Comment by artagnon** [comment]
Perl 5:

<img width="604" alt="screen shot 2015-11-13 at 10 54 27 am" src="https://cloud.githubusercontent.com/assets/37226/11150237/1c71d0b8-89f5-11e5-85f2-b4aeb8d94fe1.png">

**Comment by Fank** [comment]
@artagnon thanks for an other example, let me recheck it.

**Comment by sev-** [comment]
Another example of broken syntax highlighting at regexps:

 $a =~                     
 /\s(a+)/;

Putting these two lines anywhere makes it think the rest of the file is a regexp.

**Comment by Fank** [comment]
@sev- Why is there a reason to write a regex in multiple lines, like the example you posted?
Perl is such an dirty language, and its very hard to cover all cases.

**Comment by Fank** [comment]
I think i found the bug, PR attached above.
