### ISSUE TITLE
underscores in function names

### ISSUE THREAD

**Issue by rmetzler** [atom/language-perl#6]
Underscores in function names seem to break the highlighting

```perl
my $st_storage  = sttest($key,"t_storage",$single_task);
my $st_storage  = s_ttest($key,"t_storage",$single_task);
my $s_t_license = s__ttest($key,"t_license",$single_task);
my $s_t_addon   = sttest($key,"t_addon",$single_task);
my $s_t_links   = sttest($key,"t_links",$single_task);
my $t_case      = $value->{'time'};
```

![atom-perl-underscores-in-function-names](https://cloud.githubusercontent.com/assets/58824/6003709/f94dd9f0-aafd-11e4-93b2-8f81a2537012.png)

**Comment by Fank** [comment]
Remove following lines https://github.com/atom/language-perl/blob/1dee47a63728dcf787d710a32e323b9ecc7db45e/grammars/perl.cson#L669-L681 and it works fine. Does someone know what this regex do?
