### ISSUE TITLE
Properties named 'q' trigger the q quote highlighting

### ISSUE THREAD

**Issue by darkliquid** [atom/language-perl#7]
Atom 0.179.0 OSX, language-perl 0.10.0

In the following example, the portion of the code from q; until the next ; is erroneously highlighted as a quoted string - specifically the 2nd print keyword is highlighted as a string instead of like the other prints.

```perl
sub q() {}
my $test = {};
bless $test;
print $test->q;
# this is some code that should not be string highlighted
print "end";
```
![screencapture at thu feb 19 09 54 46 gmt 2015](https://cloud.githubusercontent.com/assets/31256/6264638/5dcc1884-b81d-11e4-86ca-31bcd20b80b4.png)

Interestingly, the highlighter github uses as well seems to make this same mistake.

**Comment by pchaigno** [comment]
> Interestingly, the highlighter github uses as well seems to make this same mistake.

@darkliquid That's because this grammar was converted from [textmate/perl.tmbundle](https://github.com/textmate/perl.tmbundle) which GitHub uses for Perl syntax highlighting (see [github/linguist](https://github.com/github/linguist) for more information). I opened an issue there.
