### ISSUE TITLE
Many symbols without scopes

### ISSUE THREAD

**Issue by chbk** [atom/language-perl#88]
A lot of punctuation and other symbols are wrongly scoped or not scoped at all. I listed here the scopes they should have imo (based on [Atom's docs](https://github.com/atom/flight-manual.atom.io/pull/114)) and a couple test cases:

Symbols | Suggested scope | Current scope | Fixed
---|---|---|---
`;` | `punctuation.terminator.semicolon` | | :white_check_mark:
`,` | `punctuation.separator.comma` | | :white_check_mark:
`::` | `punctuation.separator.colon` | | :white_check_mark:
`->` | `punctuation.separator.arrow` | `keyword.operator .comparison`  | :white_check_mark:
`=>` | `punctuation.separator.key-value` | `keyword.operator .comparison` | :white_check_mark:
`()` `[]` `{}` | `meta.function\|function-call \|method\|method-call\|arguments\|parameters` <br><br>↳ `punctuation.definition .arguments\|parameters.begin\|end .bracket.square\|curly\|round` |
`{}` | `punctuation.definition.function\|section .begin\|end.bracket.curly` |
`\@` `\%` `@$` `%$` | `punctuation.definition.variable` | | :white_check_mark:
`=` | `keyword.operator.assignement` | | :white_check_mark:
`\|\|=` `//=` | `keyword.operator.assignement.conditional` | | :white_check_mark:
`+=` `-=` `*=` `/=` `%=` `**=` | `keyword.operator.assignement.compound` | | :white_check_mark:
`&=` `\|=` `^=` | `keyword.operator.assignement.compound .bitwise` | | :white_check_mark:
`&.=` `\|.=` `^.=` | `keyword.operator.assignement.compound .stringwise` | | :white_check_mark:
`+` `-` `*` `/` `%` `**` | `keyword.operator.arithmetic` | | :white_check_mark:
`++` | `keyword.operator.increment` | | :white_check_mark:
`--` | `keyword.operator.decrement` | | :white_check_mark:
`&` `\|` `^` `~` `<<` `>>` | `keyword.operator.bitwise` | | :white_check_mark:
`&.` `\|.` `^.` `~.` | `keyword.operator.stringwise` | | :white_check_mark:
`==` `!=` `<` `>` `<=` `>=` `=~` `!~` `~~` `<=>` | `keyword.operator.comparison` | | :white_check_mark:
`eq` `ne` `lt` `gt` `le` `ge` `cmp` | `keyword.operator.comparison.stringwise` | `support.function` | :white_check_mark:
`&&` `\|\|` | `keyword.operator.logical.c-style` | | :white_check_mark:
`//` | `keyword.operator.logical.defined-or` | | :white_check_mark:
`.` | `keyword.operator.concatenation` | | :white_check_mark:
`x` | `keyword.operator.repetition` | `support.function` | :white_check_mark:
`..` `...` | `keyword.operator.range` | | :white_check_mark:
`?` `:` | `keyword.operator.ternary` | | :white_check_mark:
`<$file>` `<>` | `keyword.operator.readline` | | :white_check_mark:
`12` `57.3` | `constant.numeric.decimal` | | :white_check_mark:
`0b1110011` | `constant.numeric.binary` | | :white_check_mark:
`0x1234` | `constant.numeric.hexadecimal` | | :white_check_mark:
`12.34e-56` | `constant.numeric.exponential` | | :white_check_mark:
`state` | `storage.modifier` | | :white_check_mark:

```perl

use Physics::Gravity;                       # :: ;

Test::Subject->new;                         # :: -> ;

my $name = "Chell";                         # = ;

my $height = 162.56;                        # 162.56 ;

my @friends = ("Companion Cube");           # = () ;

my $bff = $friends[0];                      # = [] 0 ;

my $foes = ["GLaDOS", "Caroline"];          # = [] , ;

my @sing = ("triumph", "huge success");     # = () , ;

my $song = "This was a ", $sing[0], "\n";   # , [] 0 ;

my %food = (lemon => "yellow");             # = () => ;

my $color = $food{lemon};                   # = {} ;

my $company = {                             # = {
    name => "Aperture Science",             # => ,
    ceo => "Cave Johnson"                   # =>
};                                          # } ;

my $boss = $company->{ceo};                 # = -> {} ;

my $enemy = $foes -> [0];                   # = -> [] 0

if ('potato' eq 'battery') {                # () eq {

    if ('cake' ne 'lie') {                  # () ne {
        my @out = sort {$a <=> $b} @foes;   # = {} ;
    }                                       # }

    elsif (["blue", "orange"][1] lt {       # () [] , 1 lt {
        distance => 129,                    # => 129 ,
        min => 0 ,                          # => 0 ,
        max => "inf"                        # =>
    }{max}) {                               # {} ()
        my @out = sort {$a cmp $b} @foes;   # = {} cmp ;
    }                                       # }

    "we do what" lt "we must"               # lt
    "because" gt "we can"                   # gt

    "do you" le "know"                      # le
    "who i" ge "am"                         # ge
}                                           # }

while (<>) {                                # () <> {
    print('waking up subject');             # () ;
}                                           # }

my $core = <$fh>;                           # = <$fh> ;

state $temperature = 20;                    # state = 20 ;

my $array_ref = \@array;                    # = \@ ;
my $hash_ref = \%hash;                      # = \% ;

my @array = @$array_ref;                    # = @$ ;
my %hash = %$hash_ref;                      # = %$ ;

my $chamber //= 17;                         # //= 17 ;
my $chamber ||= 14;                         # ||= 14 ;

$chamber += 2;                              # += 2 ;
$chamber -= 4;                              # -= 4 ;
$chamber *= 8;                              # *= 8 ;
$chamber /= 16;                             # /= 16 ;
$chamber %= 32;                             # %= 32 ;
$chamber **= 64;                            # **= 64 ;

'150' &  '105';                             # & ;
'150' &. '105';	                            # &. ;
'150' |  '105';                             # | ;
'150' |. '105';	                            # |. ;
'150' ^  '105';                             # ^ ;
'150' ^. '105';	                            # ^. ;
'150' ~  '105';                             # ~ ;
'150' ~. '105';	                            # ~. ;

~$secret                                    # ~

1 >> 64                                     # 1 >> 64
20 << 10                                    # 20 << 10

12 &= 2                                     # 12 &= 2
24 |= 4                                     # 24 |= 4
36 ^= 6                                     # 36 ^= 6

"when"   &.= "life"                         # &.=
"gives"  |.= "you"                          # |.=
"lemons" ^.= "..."                          # ^.=

1 + 2 - 3 * 4 / 5 % 6 ** 7                  # 1 + 2 - 3 * 4 / 5 % 6 ** 7

$turret++                                   # ++
++$turret                                   # ++
$turret--                                   # --
--$turret                                   # --
++($gel = 99)                               # ++ () =
--($gel = 99)                               # -- () =

1 == 2 != 3 < 4 > 5 <= 6 >= 7               # 1 == 2 != 3 < 4 > 5 <= 6 >= 7

my $weapon =~ /neurotoxin/                  # =~
my $weapon !~ /sentry/                      # !~

$wheatley && $flashlight                     # &&
$core || $personality                       # ||
$space // $adventure                        # //

freinds[1] ~~ foes[1]                       # [] 1 ~~

my $subject = "you";                        # = ;

foreach my $i (0..9) {                      # () 0 .. 9 {

    for my $j (0...9) {                     # () 0 ... 9 {

        say $subject x $j . 'monster';      # x . ;
    }                                       # }
}                                           # }

my $end = $alive ? 'burn' : 'incinerate';   # = ? : ;
```

**Comment by chbk** [comment]
I'll tackle a couple. I'll add a checkmark next to the ones I've done.

**Comment by chbk** [comment]
I submitted a PR that fixes everything except `()`, `[]` and `{}`.

**Comment by Alhadis** [comment]
Well done, @chbk. =)

I've added generic punctuation scopes to bracket characters, because the grammar isn't structured enough to reliably recognise context for tokenised brackets. If that makes sense.

@Fank Once merged, you (or @50Wliu) should consider cutting a release for Atom users. =)
