### ISSUE TITLE
code after __DATA__ is not highlighted

### ISSUE THREAD

**Issue by paulgregg** [atom/language-perl#98]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When looking at code that ships additional perl packages as `__DATA__` blocks (.e.g amavis) atom+language-perl displays all the perl code after a `__DATA__` as comments.

### Steps to Reproduce

1. Download Amavis package https://www.amavis.org/amavisd-new-2.11.1.tar.bz2
2. Unpack
3. Open amavisd-new file (you might need to tell atom that it is Perl)
4. Search for line beginning `__DATA__` - will be ~20,000 lines down
5. Code above the `__DATA__` is perl syntax highlighted / code below the `__DATA__` is comment highlighted.

**Expected behavior:**

language-perl recognises that this is embedded perl code (this is how Amavis ships packages) and correctly syntax highlights.

**Actual behavior:**

language-perl displays the code as comments

**Reproduces how often:**

100%

### Versions

$ atom --version
Atom    : 1.39.1
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

$ apm --version
apm  2.2.4
npm  6.2.0
node 8.9.3 x64
atom 1.39.1
python 2.7.15
git 2.17.1

MacOS High Sierra 10.13.6

### Additional Information

I forked language-perl and the following patch correctly generated syntax highlighting below the `__DATA__` .   But I expect it might not like non-perl code formatted 'raw' data (which is probably why the `__DATA__` patch was added in the first place https://github.com/atom/language-perl/commit/b8f75625f7f8dfa7514ce622db9f80089e90534d).

```
diff --git a/grammars/perl.cson b/grammars/perl.cson
index ddc82df..73fb0f0 100644
--- a/grammars/perl.cson
+++ b/grammars/perl.cson
@@ -768,7 +768,7 @@
     'name': 'constant.language.perl'
   }
   {
-    'begin': '\\b(__DATA__|__END__)\\n?'
+    'begin': '\\b(__END__)\\n?'
     'captures':
       '1':
         'name': 'constant.language.perl'
```

---

*Edit by @rsese from https://github.com/atom/language-perl/issues/98#issuecomment-523311959*

With the `__DATA__` at line 19848 I see the same thing as your screenshot :+1:

Scopes at the content before and after the `__DATA__`:

![perl-data](https://user-images.githubusercontent.com/734194/63406713-4c1adc80-c3b0-11e9-9159-6db361184be3.png)

Smaller repro:

```perl
# we read text (such as notification templates) from DATA sections
# to avoid any interpretations of special characters (e.g. \ or ') by Perl
#

__DATA__
#
package Amavis::ZMQ;
use strict;
use re 'taint';
use warnings;
use warnings FATAL => qw(utf8 void);
no warnings 'uninitialized';
# use warnings 'extra'; no warnings 'experimental::re_strict'; use re 'strict';
```
I see if I comment out the `__DATA__`, the rest of the content is no longer treated as a comment.

**Comment by rsese** [comment]
Thanks for the report!  Would you be able to share a minimal example so we can just copy it directly into the issue?  About the test file you mentioned:

> * Open amavisd-new file (you might need to tell atom that it is Perl)

I don't see a `amavisd-new` file, but from my searching for `DATA`, do you mean the `amavisd` file?

> 5\. Code above the `__DATA__` is perl syntax highlighted / code below the `__DATA__` is comment highlighted.

This is what I see in Atom 1.40.0 with the first `__DATA__` at line 18903:

![perl-data](https://user-images.githubusercontent.com/734194/63293962-cf441180-c28e-11e9-9f15-ce9265c3a3e9.png)

So the highlighting seems ok after that line unless I'm misunderstanding?

**Comment by paulgregg** [comment]
Please search for the next __DATA__ (step 4) - the line beginning with __DATA__
![Screen Shot 2019-08-20 at 09 58 29](https://user-images.githubusercontent.com/3653254/63333330-2e5a6280-c331-11e9-992f-91ca5c1c124e.png)

Hopefully that makes it clearer .

**Comment by rsese** [comment]
> Please search for the next `__DATA__` (step 4) - the line beginning with `__DATA__`

Ahh sorry I misread that step, so with the `__DATA__` at line 19848 I see the same thing as your screenshot :+1:

Scopes at the content before and after the `__DATA__`:

![perl-data](https://user-images.githubusercontent.com/734194/63406713-4c1adc80-c3b0-11e9-9159-6db361184be3.png)

I've never used Perl before but to simplify things a bit, is this a valid self-contained example of the problem?  I see if I comment out the `__DATA__`, the rest of the content is no longer treated as a comment.

```perl
# we read text (such as notification templates) from DATA sections
# to avoid any interpretations of special characters (e.g. \ or ') by Perl
#

__DATA__
#
package Amavis::ZMQ;
use strict;
use re 'taint';
use warnings;
use warnings FATAL => qw(utf8 void);
no warnings 'uninitialized';
# use warnings 'extra'; no warnings 'experimental::re_strict'; use re 'strict';
```

**Comment by paulgregg** [comment]
Thanks for confirmation.
Yes, if you look at SelfLoader you'll see this is a common pattern for bundling additoonal packages without using more Files.
https://mojolicious.org/perldoc/SelfLoader

**Comment by lee-dohm** [comment]
Thanks for that link to `SelfLoader`.

While I understand that `SelfLoader` is a common use, it is only one of many possible uses of `__DATA__`. Additionally, [the `SelfLoader` documentation starts off its description of `__DATA__`](https://perldoc.perl.org/SelfLoader.html#The-__DATA__-token) as:

> The `__DATA__` token tells the perl compiler that the **perl code for compilation is finished.**

_Emphasis mine_

The fact that the `__DATA__` section can be used for storing code does not indicate that all uses of `__DATA__` are code.

So given the choice between assuming that what comes after `__DATA__` is not code when it is and assuming that what comes after `__DATA__` is code when it is not, I feel that the former hews closer to the Principle of Least Surprise. Because of this, we aren't going to be making a change like this nor would we accept a PR to make this change.

Thanks again for opening the issue and giving a well laid-out and documented use case.
